# File: core/templates/apache_vhost.j2

<VirtualHost *:8080>
    ServerName LocalWebServerStacks.test
    DocumentRoot "D:\WorkSpace\Python\LocalWebServerStacks"

    ErrorLog "D:/WorkSpace/Python/LocalWebServerStacks/core/services/webservers/bin/apache/httpd-2.4.63-250207-win64-VS17/logs/error.log"
    CustomLog "D:/WorkSpace/Python/LocalWebServerStacks/core/services/webservers/bin/apache/httpd-2.4.63-250207-win64-VS17/logs/access.log" common

    <Directory "D:\WorkSpace\Python\LocalWebServerStacks">
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Require all granted
    </Directory>


    # ---- Dành cho dự án Proxy ----
    ProxyRequests Off
    ProxyPreserveHost On
    ProxyPass / http://127.0.0.1:8002/
    ProxyPassReverse / http://127.0.0.1:8002/


</VirtualHost>

